name: assessment2023
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  dio: ^5.4.0
  flutter_bloc: ^8.1.3
  get_it: ^7.6.4
  url_launcher: ^6.2.2
  get_storage: ^2.1.1
  google_fonts: ^6.1.0 
  flutter_dotenv: ^5.1.0
  cached_network_image: ^3.3.0

dev_dependencies:

  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

  


flutter:
  uses-material-design: true
  assets:
    - .env